In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df = pandas.read_csv("/content/drive/MyDrive/sample datasets/book1.csv")

In [ ]:
df


petrol  vegetables  food
0      90          50    20
1      91          55    21
2      95          60    22
3      97          62    24
4      99          65    28
5     100          75    30
6     105          80    35
7     110          85    40

In [ ]:
x=df.drop(['food'],axis=1)
y=df['food']

In [ ]:
type(x)
type(y)

pandas.core.series.Series

In [ ]:
x=x.values
y=y.values

In [ ]:
type(x)
type(y)

numpy.ndarray

In [ ]:
# splliting the database into training set and testing set
from sklearn.model_selection import train_test_split

x_training_set,x_testing_set,y_training_set,y_testing_set=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_training_set

array([[ 91,  55],
       [110,  85],
       [ 97,  62],
       [ 90,  50],
       [100,  75],
       [ 99,  65]])

In [ ]:
x_testing_set

array([[105,  80],
       [ 95,  60]])

In [ ]:
y_training_set

array([21, 40, 24, 20, 30, 28])

In [ ]:
y_testing_set

array([35, 22])

In [ ]:
# fitting multiple linear regression to the training set

from sklearn.linear_model import LinearRegression

regressor=LinearRegression()
regressor.fit(x_training_set,y_training_set)

LinearRegression()

In [ ]:
regressor

LinearRegression()

In [ ]:
#the coefficients

print('Coefficient: \n',regressor.coef_)

Coefficient: 
 [0.73563502 0.15621455]


In [ ]:
regressor.intercept_

-55.008976572133164

In [ ]:
# prediciting the test set results

y_pred=regressor.predict(x_testing_set)
y_pred

array([34.72986436, 24.24922318])

In [ ]:
from sklearn.metrics import mean_squared_error

# the mean squared error

print("Mean squared error:",mean_squared_error(y_testing_set,y_pred))

Mean squared error: 2.565989090206968


In [ ]:
# explained variance score: 1 is prefect prediction
from sklearn.metrics import r2_score

print('Variance score:',r2_score(y_testing_set,y_pred))

Variance score: 0.9392665304093025


In [ ]:
# compare actual data with predicted value
import pandas as pd
y_test=pd.DataFrame(y_testing_set)
y_prediction=pd.DataFrame(y_pred)

comparison=pd.concat([y_test,y_prediction],axis=1)


In [ ]:
comparison.to_csv('regression comparison.csv')

In [ ]:
comparison

0          0
0  35  34.729864
1  22  24.249223

In [ ]:
df

petrol  vegetables  food
0      90          50    20
1      91          55    21
2      95          60    22
3      97          62    24
4      99          65    28
5     100          75    30
6     105          80    35
7     110          85    40

In [ ]:
df.columns

Index(['petrol', 'vegetables', 'food'], dtype='object')

In [ ]:
x=df.drop(['food'],axis=1)
y=df['food']

In [ ]:
x=sm.add_constant(x)

model = sm.OLS(y, x).fit()  # ordinary least square(OLS)

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [ ]:
summary = model.summary()
print(summary)

                            OLS Regression Results                            
Dep. Variable:                   food   R-squared:                       0.971
Model:                            OLS   Adj. R-squared:                  0.960
Method:                 Least Squares   F-statistic:                     84.10
Date:                Fri, 06 May 2022   Prob (F-statistic):           0.000142
Time:                        04:43:08   Log-Likelihood:                -12.398
No. Observations:                   8   AIC:                             30.80
Df Residuals:                       5   BIC:                             31.03
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -55.0356     22.399     -2.457      0.0

/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))


In [ ]:
# calculation of VIF for each explanatory variable

from statsmodels.stats.outliers_influence import variance_inflation_factor

vif=pd.DataFrame()
vif['VIF']=[variance_inflation_factor(x.values,i) for i in range(x.shape[1])]
vif['variables']=x.columns
print(vif)

           VIF   variables
0  1930.921802       const
1    19.162480      petrol
2    19.162480  vegetables


In [1]:
# linear reggression using Gradient Decent method 

import numpy as np
import matplotlib.pyplot as plt

x=2*np.random.rand(100,1)
y=4+3*x+np.random.rand(100,1)

In [13]:
#linear reggression using OLS

from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(x,y)
lin_reg.intercept_
lin_reg.coef_


array([[2.99536781]])

In [12]:
from sklearn.linear_model import SGDRegressor

sgd_reg=SGDRegressor(n_iter=50, penalty=None, eta0=0.1)
sgd_reg.fit(x,y.ravel())
sgd_reg.intercept_
sgd_reg.coef_


TypeError: ignored