In [36]:
# for h1n1_vaccine_prediction.csv (logistic regression) 


from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [60]:
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/0.MKCE/3.Logistic Regression/2 Project/Vaccine Usage Prediction/Dataset/h1n1_vaccine_prediction.csv')

In [46]:
df

unique_id  h1n1_worry  h1n1_awareness  antiviral_medication  \
0              0         1.0             0.0                   0.0   
1              1         3.0             2.0                   0.0   
2              2         1.0             1.0                   0.0   
3              3         1.0             1.0                   0.0   
4              4         2.0             1.0                   0.0   
...          ...         ...             ...                   ...   
26702      26702         2.0             0.0                   0.0   
26703      26703         1.0             2.0                   0.0   
26704      26704         2.0             2.0                   0.0   
26705      26705         1.0             1.0                   0.0   
26706      26706         0.0             0.0                   0.0   

       contact_avoidance  bought_face_mask  wash_hands_frequently  \
0                    0.0               0.0                    0.0   
1                    1.0               0.0                    1.0   
2                    1.0               0.0                    0.0   
3                    1.0               0.0                    1.0   
4                    1.0               0.0                    1.0   
...                  ...               ...                    ...   
26702                1.0               0.0                    0.0   
26703                1.0               0.0                    1.0   
26704                1.0               1.0                    1.0   
26705                0.0               0.0                    0.0   
26706                1.0               0.0                    0.0   

       avoid_large_gatherings  reduced_outside_home_cont  avoid_touch_face  \
0                         0.0                        1.0               1.0   
1                         0.0                        1.0               1.0   
2                         0.0                        0.0               0.0   
3                         1.0                        0.0               0.0   
4                         1.0                        0.0               1.0   
...                       ...                        ...               ...   
26702                     0.0                        1.0               0.0   
26703                     0.0                        0.0               0.0   
26704                     1.0                        0.0               1.0   
26705                     0.0                        0.0               NaN   
26706                     0.0                        0.0               0.0   

       ...      race     sex               income_level  marital_status  \
0      ...     White  Female              Below Poverty     Not Married   
1      ...     White    Male              Below Poverty     Not Married   
2      ...     White    Male  <= $75,000, Above Poverty     Not Married   
3      ...     White  Female              Below Poverty     Not Married   
4      ...     White  Female  <= $75,000, Above Poverty         Married   
...    ...       ...     ...                        ...             ...   
26702  ...     White  Female  <= $75,000, Above Poverty     Not Married   
26703  ...     White    Male  <= $75,000, Above Poverty     Not Married   
26704  ...     White  Female                        NaN     Not Married   
26705  ...  Hispanic  Female  <= $75,000, Above Poverty         Married   
26706  ...     White    Male  <= $75,000, Above Poverty         Married   

       housing_status          employment                census_msa  \
0                 Own  Not in Labor Force                   Non-MSA   
1                Rent            Employed  MSA, Not Principle  City   
2                 Own            Employed  MSA, Not Principle  City   
3                Rent  Not in Labor Force       MSA, Principle City   
4                 Own            Employed  MSA, Not Principle  City   
...               ...                 ...                       ...   
26

In [61]:
# dummies

df=pd.get_dummies(df)



In [62]:
# dropping NA

df.dropna(axis=0,inplace=True)


In [63]:
# splitting
import numpy as np

x = df.drop(['h1n1_vaccine'],axis=1).values
y = df['h1n1_vaccine'].values

In [110]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [116]:
# logistic regression

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

In [117]:
model.fit(x_train,y_train)

LogisticRegression()

In [118]:
# prediction 

y_pred=model.predict(x_test)

y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [119]:
# probability of occurence 0 or 1 in place of corresponding x_test values

model.predict_proba(x_test)

array([[0.64173207, 0.35826793],
       [0.73789859, 0.26210141],
       [0.81764353, 0.18235647],
       ...,
       [0.95227991, 0.04772009],
       [0.96170643, 0.03829357],
       [0.88122054, 0.11877946]])

In [120]:
# measuring the accuracy of model

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy_score(y_test,y_pred)

0.7990377498149519

In [121]:
confusion_matrix(y_test,y_pred)

array([[1688,  184],
       [ 359,  471]])

In [122]:
z=classification_report(y_test,y_pred)
print(z)

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1872
           1       0.72      0.57      0.63       830

    accuracy                           0.80      2702
   macro avg       0.77      0.73      0.75      2702
weighted avg       0.79      0.80      0.79      2702

