In [1]:
# for HR_comma_sep.csv

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/0.MKCE/Datasets/HR_comma_sep.csv')

In [3]:
df

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years Department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14994                      0    support     low  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  

[14999 rows x 10 columns]

In [29]:
# splitting
import numpy as np

#x = df.drop(['left','Department','salary'],axis=1).values
x = df.select_dtypes(include=np.number)
y = df['left'].values
x.drop(['left'],axis=1)

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  \
0                       157                   3              0   
1                       262                   6              0   
2                       272                   4              0   
3                       223                   5              0   
4                       159                   3              0   
...                     ...                 ...            ...   
14994                   151                   3              0   
14995                   160                   3              0   
14996                   143                   3              0   
14997                   280                   4              0   
14998                   158                   3              0   

       promotion_last_5years  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  
...                      ...  
14994                      0  
14995                      0  
14996                      0  
14997                      0  
14998                      0  

[14999 rows x 7 columns]

In [30]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [31]:
# logistic regression

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

In [32]:
df.dtypes

satisfaction_level       float64
last_evaluation          float64
number_project             int64
average_montly_hours       int64
time_spend_company         int64
Work_accident              int64
left                       int64
promotion_last_5years      int64
Department                object
salary                    object
dtype: object

In [33]:
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [34]:
# prediction 

y_pred=model.predict(x_test)

y_pred

array([1, 0, 0, ..., 1, 0, 0])

In [63]:
# probability of occurence 0 or 1 in place of corresponding x_test values

model.predict_proba(x_test)

array([[2.25405268e-03, 9.97745947e-01],
       [9.98714124e-01, 1.28587587e-03],
       [9.99230345e-01, 7.69655475e-04],
       ...,
       [2.29616914e-03, 9.97703831e-01],
       [9.98016644e-01, 1.98335587e-03],
       [9.97044124e-01, 2.95587623e-03]])

In [62]:
x_test

array([[0.44, 0.57, 2.  , ..., 0.  , 0.  , 1.  ],
       [0.55, 0.96, 3.  , ..., 0.  , 0.  , 1.  ],
       [0.72, 0.67, 5.  , ..., 0.  , 0.  , 1.  ],
       ...,
       [0.37, 0.54, 2.  , ..., 0.  , 0.  , 1.  ],
       [0.52, 0.61, 4.  , ..., 1.  , 1.  , 0.  ],
       [0.13, 0.65, 4.  , ..., 0.  , 0.  , 1.  ]])

In [64]:
# measuring the accuracy of model

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy_score(y_test,y_pred)

1.0

In [1]:
confusion_matrix(y_test,y_pred)

NameError: ignored

In [56]:
z=classification_report(y_test,y_pred)
print(z)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2299
           1       1.00      1.00      1.00       701

    accuracy                           1.00      3000
   macro avg       1.00      1.00      1.00      3000
weighted avg       1.00      1.00      1.00      3000



In [59]:
# filter out the numerical variables and consider only the categorical variables using (include=object)
df_categoric = df.select_dtypes(include = object)

# display categorical features
df_categoric.columns

Index(['Department', 'salary'], dtype='object')

In [42]:
# to create the dummy variables  we use 'get_dummies()' from pandas 
# to create (n-1) dummy variables we use 'drop_first = True' 
dummy = pd.get_dummies(df_categoric, drop_first = True)

In [44]:
# concatenate the numerical and dummy encoded categorical variables column-wise
df_dummy = pd.concat([x, dummy], axis=1)

# display data with dummy variables
df_dummy.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   
4                   3              0     1                      0   

   Department_RandD  Department_accounting  Department_hr  \
0                 0                      0              0   
1                 0                      0              0   
2                 0                      0              0   
3                 0                      0              0   
4                 0                      0              0   

   Department_management  Department_marketing  Department_product_mng  \
0                      0                     0                       0   
1                      0                     0                       0   
2                      0                     0                       0   
3                      0                     0                       0   
4                      0                     0                       0   

   Department_sales  Department_support  Department_technical  salary_low  \
0                 1                   0                     0           1   
1                 1                   0                     0           0   
2                 1                   0                     0           0   
3                 1                   0                     0           1   
4                 1                   0                     0           1   

   salary_medium  
0              0  
1              1  
2              1  
3              0  
4              0

In [46]:
df_dummy

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years  Department_RandD  Department_accounting  \
0                          0                 0                      0   
1                          0                 0                      0   
2                          0                 0                      0   
3                          0                 0                      0   
4                          0                 0                      0   
...                      ...               ...                    ...   
14994                      0                 0                      0   
14995                      0                 0                      0   
14996                      0                 0                      0   
14997                      0                 0                      0   
14998                      0                 0                      0   

       Department_hr  Department_management  Department_marketing  \
0                  0                      0                     0   
1                  0                      0                     0   
2                  0                      0                     0   
3                  0                      0                     0   
4                  0                      0                     0   
...              ...                    ...                   ...   
14994              0                      0                     0   
14995              0                      0                     0   
14996              0                      0                     0   
14997              0                      0                     0   
14998              0                      0                     0   

       Department_product_mng  Department_sales  Department_support  \
0                           0                 1                   0   
1                           0                 1                   0   
2                           0                 1                   0   
3                           0                 1                   0   
4                           0                 1                   0   
...                       ...               ...                 ...   
14994                       0                 0                   1   
14995                       0                 0                   1   
14996                       0                 0     

In [47]:
# splitting

x = df_dummy.values
y = df['left'].values


In [48]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [49]:
# logistic regression

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

In [50]:
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [51]:
# prediction 

y_pred=model.predict(x_test)

y_pred

array([1, 0, 0, ..., 1, 0, 0])

In [52]:
# probability of occurence 0 or 1 in place of corresponding x_test values

model.predict_proba(x_test)

array([[2.25405268e-03, 9.97745947e-01],
       [9.98714124e-01, 1.28587587e-03],
       [9.99230345e-01, 7.69655475e-04],
       ...,
       [2.29616914e-03, 9.97703831e-01],
       [9.98016644e-01, 1.98335587e-03],
       [9.97044124e-01, 2.95587623e-03]])

In [53]:
# measuring the accuracy of model

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy_score(y_test,y_pred)

1.0

In [54]:
confusion_matrix(y_test,y_pred)

array([[2299,    0],
       [   0,  701]])

In [55]:
z=classification_report(y_test,y_pred)
print(z)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2299
           1       1.00      1.00      1.00       701

    accuracy                           1.00      3000
   macro avg       1.00      1.00      1.00      3000
weighted avg       1.00      1.00      1.00      3000



In [61]:
df_property_dummy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   satisfaction_level      14999 non-null  float64
 1   last_evaluation         14999 non-null  float64
 2   number_project          14999 non-null  int64  
 3   average_montly_hours    14999 non-null  int64  
 4   time_spend_company      14999 non-null  int64  
 5   Work_accident           14999 non-null  int64  
 6   left                    14999 non-null  int64  
 7   promotion_last_5years   14999 non-null  int64  
 8   Department_RandD        14999 non-null  uint8  
 9   Department_accounting   14999 non-null  uint8  
 10  Department_hr           14999 non-null  uint8  
 11  Department_management   14999 non-null  uint8  
 12  Department_marketing    14999 non-null  uint8  
 13  Department_product_mng  14999 non-null  uint8  
 14  Department_sales        14999 non-null